"""project version overrides

Revision ID: a9a67db0647a
Revises: bc542dd40e26
Create Date: 2026-08-17 16:05:05.117839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a67db0647a'
down_revision: Union[str, Sequence[str], None] = 'bc542dd40e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'overrides')
    # ### end Alembic commands ###
