"""event_cursor

Revision ID: bc542dd40e26
Revises: 6361f40745e1
Create Date: 2026-08-17 14:30:09.819853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc542dd40e26'
down_revision: Union[str, Sequence[str], None] = '6361f40745e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('last_seen_at', sa.String(length=40), nullable=True),
    sa.Column('last_seen_sha', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name', 'repo_url', name='uq_cursor_project_repo')
    )
    op.create_index(op.f('ix_event_cursor_project_name'), 'event_cursor', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_cursor_project_name'), table_name='event_cursor')
    op.drop_table('event_cursor')
    # ### end Alembic commands ###
